import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/stories/templates/Header";
import { TbRectangle, TbRectangleFilled } from "react-icons/tb";
import { TbTriangle, TbTriangleFilled } from "react-icons/tb";
import { TbOctagon, TbOctagonFilled } from "react-icons/tb";
import { TbBook, TbBookFilled } from "react-icons/tb";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const appInfo = {
  img: "/logo_type_a.png",
  href: "/",
};
const headerInfo = [
  {
    label: "플로우",
    IconNonSel: <TbRectangle />,
    IconSel: <TbRectangleFilled />,
    href: "/flow",
  },
  {
    label: "대시보드",
    IconNonSel: <TbTriangle />,
    IconSel: <TbTriangleFilled />,
    href: "/dashboard",
  },
  {
    label: "데이터셋",
    IconNonSel: <TbBook />,
    IconSel: <TbBookFilled />,
    href: "/dataset",
  },
  {
    label: "모델관리",
    IconNonSel: <TbOctagon />,
    IconSel: <TbOctagonFilled />,
    href: "/models",
  },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" h-full">
      <body className={inter.className + " h-full self-auto box-border"}>
        <div className=" flex flex-col h-full overflow-y-auto">
          <div className=" grow relative flex flex-col overflow-y-auto overflow-x-hidden bg-background-body">
            <Header appInfo={appInfo} headerInfo={headerInfo} />
            <div className=" relative flex flex-col overflow-y-auto bg-gray-100 shrink-0 h-0 grow">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
